### ISSUE TITLE
Problem on PDF catalogue on Open Cart v1.5.5.1

### ISSUE THREAD

**Issue by bodochung** [mithereal/opencart-pdf-catalog#4]
Hi,

I've just installed the pdf catalogue extension v 2b and the Tcpdf version 6 on Open Cart 1.5.5.1.

After I've properly set on the moduel and the relevatn pdf catalogue dropdown box on the web page, I encountered an error problem. The error is listed below.

Warning: file_exists() [function.file-exists]: open_basedir restriction in effect. File(../../../../image/data/BeadsOkLogo/Beads OK Logo 310x90.png) is not within the allowed path(s): (/var/www/vhosts/beadsok.com/httpdocs:/tmp) in /var/www/vhosts/beadsok.com/httpdocs/catalog/controller/product/pdf_catalog.php on line 95TCPDF ERROR: Some data has already been output, can't send PDF file

Would you please help me solve this error?

Looking forward to your reply.

Thanks!

Bodo

**Comment by mithereal** [comment]
try removing the image file located at ../../../../image/data/BeadsOkLogo/Beads
OK Logo 310x90.png the script should fix itself,

**Comment by bodochung** [comment]
Hi,
I already tried to remove the image file, but the error still happens. Moreover, this image is my shop logo image so it logically should not be supposed to remove it when using this pdf extension.

Would you please help check my error again?

Thanks!

Bodo

**Comment by bodochung** [comment]
Sorry for pressing the wrong button to close this issue. I copied my problem again below and wait for your help. Thanks!

Hi,
I already tried to remove the image file, but the error still happens. Moreover, this image is my shop logo image so it logically should not be supposed to remove it when using this pdf extension.

Would you please help check my error again?

Thanks!

Bodo

**Comment by mithereal** [comment]
closing issue as reuppung a new version, reopen if issue is still not fixed
